services:
  - type: web
    name: aitextcoach
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: python server.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PAYPAL_CLIENT_ID
        value: AdtYR0zkWzQfqViuiRqDPao6Dp1nwr-nXNNcBG3scWj0BFr3_zUTc-1IsGf95NqDb2gLaD8S20LLaFBl
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_MODE
        value: sandbox
      - key: PAYPAL_PLAN_ID
        value: P-7SB75295DK0602635NJFH34Q
