services:
  - type: web
    name: aitextcoach
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aitextcoach-db
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false
      - key: PAYPAL_CLIENT_ID
        value: AdtYR0zkWzQfqViuiRqDPao6Dp1nwr-nXNNcBG3scWj0BFr3_zUTc-1IsGf95NqDb2gLaD8S20LLaFBl
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_MODE
        value: sandbox
      - key: PAYPAL_PLAN_ID
        value: P-7SB75295DK0602635NJFH34Q

databases:
  - name: aitextcoach-db
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
